// ── JanSetu Gov Design Tokens ──────────────────────────────
export const COLORS = {
  primary: "#FF6B35",       // Deep Saffron
  navy: "#0A192F",          // Deep Navy
  brickRed: "#D32F2F",      // Anomaly / destructive
  success: "#2E7D32",       // Green for good utilization
  warning: "#F57F17",       // Amber for medium anomalies
  background: "#FFFFFF",
  cardBg: "#F8F9FA",
  border: "#E0E4EA",
  muted: "#6B7280",
  textDark: "#0A192F",
};

export const DEMO_BADGE = "Demo Mode — Synthetic Data";
export const DEMO_DATASET_LABEL = "Demo Dataset — Verify with Official Source";

// ── Languages ─────────────────────────────────────────────
export type LangCode =
  | "en" | "hi" | "as" | "bn"
  | "mr" | "gu" | "ta" | "te" | "kn" | "pa" | "or" | "ur" | "ne" | "ml" | "sa" | "kok" | "mai";

export const LANGUAGES: { code: LangCode; label: string; nativeLabel: string }[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "hi", label: "Hindi", nativeLabel: "हिंदी" },
  { code: "as", label: "Assamese", nativeLabel: "অসমীয়া" },
  { code: "bn", label: "Bengali", nativeLabel: "বাংলা" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी" },
  { code: "gu", label: "Gujarati", nativeLabel: "ગુજરાતી" },
  { code: "ta", label: "Tamil", nativeLabel: "தமிழ்" },
  { code: "te", label: "Telugu", nativeLabel: "తెలుగు" },
  { code: "kn", label: "Kannada", nativeLabel: "ಕನ್ನಡ" },
  { code: "pa", label: "Punjabi", nativeLabel: "ਪੰਜਾਬੀ" },
  { code: "or", label: "Odia", nativeLabel: "ଓଡ଼ିଆ" },
  { code: "ur", label: "Urdu", nativeLabel: "اردو" },
  { code: "ne", label: "Nepali", nativeLabel: "नेपाली" },
  { code: "ml", label: "Malayalam", nativeLabel: "മലയാളം" },
  { code: "sa", label: "Sanskrit", nativeLabel: "संस्कृतम्" },
  { code: "kok", label: "Konkani", nativeLabel: "कोंकणी" },
  { code: "mai", label: "Maithili", nativeLabel: "मैथिली" },
];

// ── Indian Number Formatting ───────────────────────────────
export function formatINR(crore: number): string {
  if (crore >= 100) return `₹${(crore / 100).toFixed(1)} Hundred Cr`;
  if (crore >= 1) return `₹${crore.toFixed(2)} Cr`;
  const lakh = crore * 100;
  if (lakh >= 1) return `₹${lakh.toFixed(1)} L`;
  return `₹${(crore * 10000000).toLocaleString("en-IN")}`;
}

export function formatBeneficiaries(n: number): string {
  if (n >= 100000) return `${(n / 100000).toFixed(1)}L`;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}K`;
  return String(n);
}

// ── States & Districts ─────────────────────────────────────
export const STATES_DISTRICTS: Record<string, string[]> = {
  Assam: ["Kamrup", "Jorhat", "Dibrugarh", "Guwahati", "Nagaon"],
  Bihar: ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga"],
  Jharkhand: ["Ranchi", "Dhanbad", "Jamshedpur", "Bokaro", "Hazaribagh"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri"],
  "Uttar Pradesh": ["Lucknow", "Varanasi", "Agra", "Kanpur", "Allahabad"],
  Maharashtra: ["Pune", "Mumbai", "Nagpur", "Nashik", "Aurangabad"],
};

export const FINANCIAL_YEARS = ["2024-25", "2023-24", "2022-23"];

// ── Scheme Categories ──────────────────────────────────────
export const SCHEME_CATEGORIES = [
  "Agriculture",
  "Education",
  "Women & Child",
  "Health",
  "Housing",
  "Employment",
  "MSME",
  "Senior Citizens",
  "Scholarships",
  "Rural Development",
];

export const CATEGORY_ICONS: Record<string, string> = {
  Agriculture: "🌾",
  Education: "🎓",
  "Women & Child": "👩‍👧",
  Health: "🏥",
  Housing: "🏠",
  Employment: "💼",
  MSME: "🏭",
  "Senior Citizens": "👴",
  Scholarships: "📚",
  "Rural Development": "🌱",
};

// ── Lifecycle steps ────────────────────────────────────────
export const LIFECYCLE_STEPS = [
  "Discover",
  "Check Eligibility",
  "Apply",
  "Govt Funding",
  "Implementation",
  "Public Transparency",
];

// ── Translations ───────────────────────────────────────────
export const T: Record<LangCode, Record<string, string>> = {
  en: {
    appName: "JanSetu Gov",
    tagline: "From Scheme Discovery to Government Accountability",
    findMySchemes: "Find My Schemes",
    govDashboard: "Government Dashboard",
    publicView: "Public Transparency",
    speakToSearch: "Speak to Search",
    orTypeHere: "Or type your query here...",
    listening: "Listening...",
    searchSchemes: "Search schemes...",
    mySchemes: "My Schemes",
    profile: "Profile",
    home: "Home",
    search: "Search",
    eligibility: "Eligibility",
    benefits: "Benefits",
    documents: "Documents",
    applyNow: "Apply Now",
    checkEligibility: "Check My Eligibility",
    bookmark: "Bookmark",
    bookmarked: "Bookmarked",
    demoMode: "Demo Mode",
    voicePromptHint: 'Try: "I am a farmer with 2 acres, need financial help"',
    language: "Language",
    logout: "Logout",
    saveScheme: "Save Scheme",
    applicationStatus: "Application Status",
    submitted: "Submitted",
    under_review: "Under Review",
    approved: "Approved",
    disbursed: "Disbursed",
    selectRole: "Select Your Role",
    citizen: "Citizen",
    officer: "Government Officer",
    publicViewer: "Public Viewer",
  },
  hi: {
    appName: "जनसेतु गव",
    tagline: "योजना खोज से सरकारी जवाबदेही तक",
    findMySchemes: "मेरी योजनाएं खोजें",
    govDashboard: "सरकारी डैशबोर्ड",
    publicView: "सार्वजनिक पारदर्शिता",
    speakToSearch: "खोजने के लिए बोलें",
    orTypeHere: "या यहाँ टाइप करें...",
    listening: "सुन रहा है...",
    searchSchemes: "योजनाएं खोजें...",
    mySchemes: "मेरी योजनाएं",
    profile: "प्रोफाइल",
    home: "होम",
    search: "खोज",
    eligibility: "पात्रता",
    benefits: "लाभ",
    documents: "दस्तावेज़",
    applyNow: "अभी आवेदन करें",
    checkEligibility: "पात्रता जांचें",
    bookmark: "सहेजें",
    bookmarked: "सहेजा गया",
    demoMode: "डेमो मोड",
    voicePromptHint: 'कहें: "मेरे पास 2 एकड़ जमीन है, खेती के लिए मदद चाहिए"',
    language: "भाषा",
    logout: "लॉग आउट",
    saveScheme: "योजना सहेजें",
    applicationStatus: "आवेदन स्थिति",
    submitted: "जमा किया",
    under_review: "समीक्षाधीन",
    approved: "स्वीकृत",
    disbursed: "वितरित",
    selectRole: "अपनी भूमिका चुनें",
    citizen: "नागरिक",
    officer: "सरकारी अधिकारी",
    publicViewer: "सार्वजनिक दर्शक",
  },
  as: {
    appName: "জনসেতু গভ",
    tagline: "আঁচনি আৱিষ্কাৰৰ পৰা চৰকাৰী দায়বদ্ধতালৈ",
    findMySchemes: "মোৰ আঁচনি বিচাৰক",
    govDashboard: "চৰকাৰী ড্যাশবোর্ড",
    publicView: "ৰাজহুৱা স্বচ্ছতা",
    speakToSearch: "সন্ধানৰ বাবে কথা কওক",
    orTypeHere: "বা ইয়াত টাইপ কৰক...",
    listening: "শুনিছে...",
    searchSchemes: "আঁচনি বিচাৰক...",
    mySchemes: "মোৰ আঁচনিসমূহ",
    profile: "প্ৰ'ফাইল",
    home: "হোম",
    search: "সন্ধান",
    eligibility: "যোগ্যতা",
    benefits: "সুবিধা",
    documents: "নথিপত্ৰ",
    applyNow: "এতিয়া আবেদন কৰক",
    checkEligibility: "যোগ্যতা পৰীক্ষা কৰক",
    bookmark: "সংৰক্ষণ",
    bookmarked: "সংৰক্ষিত",
    demoMode: "ডেমো মোড",
    voicePromptHint: 'কওক: "মোৰ 2 বিঘা মাটি আছে, খেতিৰ বাবে সহায় লাগে"',
    language: "ভাষা",
    logout: "লগ আউট",
    saveScheme: "আঁচনি সংৰক্ষণ",
    applicationStatus: "আবেদনৰ অৱস্থা",
    submitted: "দাখিল কৰা হৈছে",
    under_review: "পৰ্যালোচনাধীন",
    approved: "অনুমোদিত",
    disbursed: "বিতৰণ কৰা হৈছে",
    selectRole: "আপোনাৰ ভূমিকা বাছক",
    citizen: "নাগৰিক",
    officer: "চৰকাৰী বিষয়া",
    publicViewer: "ৰাজহুৱা দৰ্শক",
  },
  bn: {
    appName: "জনসেতু গভ",
    tagline: "প্রকল্প আবিষ্কার থেকে সরকারি জবাবদিহিতা",
    findMySchemes: "আমার প্রকল্প খুঁজুন",
    govDashboard: "সরকারি ড্যাশবোর্ড",
    publicView: "সার্বজনীন স্বচ্ছতা",
    speakToSearch: "অনুসন্ধানের জন্য বলুন",
    orTypeHere: "বা এখানে টাইপ করুন...",
    listening: "শুনছে...",
    searchSchemes: "প্রকল্প খুঁজুন...",
    mySchemes: "আমার প্রকল্প",
    profile: "প্রোফাইল",
    home: "হোম",
    search: "অনুসন্ধান",
    eligibility: "যোগ্যতা",
    benefits: "সুবিধা",
    documents: "নথিপত্র",
    applyNow: "এখনই আবেদন করুন",
    checkEligibility: "যোগ্যতা যাচাই করুন",
    bookmark: "সংরক্ষণ",
    bookmarked: "সংরক্ষিত",
    demoMode: "ডেমো মোড",
    voicePromptHint: 'বলুন: "আমার ২ বিঘা জমি আছে, কৃষির জন্য সাহায্য দরকার"',
    language: "ভাষা",
    logout: "লগ আউট",
    saveScheme: "প্রকল্প সংরক্ষণ",
    applicationStatus: "আবেদনের অবস্থা",
    submitted: "জমা দেওয়া হয়েছে",
    under_review: "পর্যালোচনাধীন",
    approved: "অনুমোদিত",
    disbursed: "বিতরণ করা হয়েছে",
    selectRole: "আপনার ভূমিকা বেছে নিন",
    citizen: "নাগরিক",
    officer: "সরকারি কর্মকর্তা",
    publicViewer: "সার্বজনীন দর্শক",
  },
  mr: {
    appName: "जनसेतू गव्ह",
    tagline: "योजना शोधण्यापासून सरकारी उत्तरदायित्वापर्यंत",
    findMySchemes: "माझ्या योजना शोधा",
    govDashboard: "सरकारी डॅशबोर्ड",
    publicView: "सार्वजनिक पारदर्शकता",
    speakToSearch: "शोधण्यासाठी बोला",
    orTypeHere: "किंवा येथे टाइप करा...",
    listening: "ऐकत आहे...",
    searchSchemes: "योजना शोधा...",
    mySchemes: "माझ्या योजना",
    profile: "प्रोफाइल",
    home: "मुख्यपृष्ठ",
    search: "शोध",
    eligibility: "पात्रता",
    benefits: "लाभ",
    documents: "कागदपत्रे",
    applyNow: "आता अर्ज करा",
    checkEligibility: "पात्रता तपासा",
    bookmark: "जतन करा",
    bookmarked: "जतन केले",
    demoMode: "डेमो मोड",
    voicePromptHint: 'सांगा: "माझ्याकडे 2 एकर जमीन आहे, शेतीसाठी मदत हवी आहे"',
    language: "भाषा",
    logout: "बाहेर पडा",
    saveScheme: "योजना जतन करा",
    applicationStatus: "अर्जाची स्थिती",
    submitted: "सादर केले",
    under_review: "पुनरावलोकनाधीन",
    approved: "मंजूर",
    disbursed: "वितरित",
    selectRole: "तुमची भूमिका निवडा",
    citizen: "नागरिक",
    officer: "सरकारी अधिकारी",
    publicViewer: "सार्वजनिक दर्शक",
  },
  gu: {
    appName: "જનસેતુ ગવ",
    tagline: "યોજના શોધથી સરકારી જવાબદારી સુધી",
    findMySchemes: "મારી યોજનાઓ શોધો",
    govDashboard: "સરકારી ડેશબોર્ડ",
    publicView: "જાહેર પારદર્શિતા",
    speakToSearch: "શોધવા માટે બોલો",
    orTypeHere: "અથવા અહીં ટાઇપ કરો...",
    listening: "સાંભળી રહ્યું છે...",
    searchSchemes: "યોજનાઓ શોધો...",
    mySchemes: "મારી યોજનાઓ",
    profile: "પ્રોફાઇલ",
    home: "હોમ",
    search: "શોધ",
    eligibility: "પાત્રતા",
    benefits: "લાભો",
    documents: "દસ્તાવેજો",
    applyNow: "હમણાં અરજી કરો",
    checkEligibility: "પાત્રતા ચકાસો",
    bookmark: "સાચવો",
    bookmarked: "સાચવેલ",
    demoMode: "ડેમો મોડ",
    voicePromptHint: 'કહો: "મારી પાસે 2 એકર જમીન છે, ખેતી માટે મદદ જોઈએ છે"',
    language: "ભાષા",
    logout: "લોગ આઉટ",
    saveScheme: "યોજના સાચવો",
    applicationStatus: "અરજીની સ્થિતિ",
    submitted: "સબમિટ કર્યું",
    under_review: "સમીક્ષા હેઠળ",
    approved: "મંજૂર",
    disbursed: "વિતરિત",
    selectRole: "તમારી ભૂમિકા પસંદ કરો",
    citizen: "નાગરિક",
    officer: "સરકારી અધિકારી",
    publicViewer: "જાહેર દર્શક",
  },
  ta: {
    appName: "ஜன்செது கவ்",
    tagline: "திட்ட கண்டறிதலில் இருந்து அரசு பொறுப்புக்கூறல் வரை",
    findMySchemes: "எனது திட்டங்களைக் கண்டறியவும்",
    govDashboard: "அரசு டாஷ்போர்டு",
    publicView: "பொது வெளிப்படைத்தன்மை",
    speakToSearch: "தேட பேசவும்",
    orTypeHere: "அல்லது இங்கே தட்டச்சு செய்யவும்...",
    listening: "கேட்கிறது...",
    searchSchemes: "திட்டங்களைத் தேடவும்...",
    mySchemes: "எனது திட்டங்கள்",
    profile: "சுயவிவரம்",
    home: "முகப்பு",
    search: "தேடல்",
    eligibility: "தகுதி",
    benefits: "பலன்கள்",
    documents: "ஆவணங்கள்",
    applyNow: "இப்போது விண்ணப்பிக்கவும்",
    checkEligibility: "தகுதியை சரிபார்க்கவும்",
    bookmark: "சேமிக்கவும்",
    bookmarked: "சேமிக்கப்பட்டது",
    demoMode: "டெமோ முறை",
    voicePromptHint: 'சொல்லுங்கள்: "என்னிடம் 2 ஏக்கர் நிலம் உள்ளது, விவசாயத்திற்கு உதவி தேவை"',
    language: "மொழி",
    logout: "வெளியேறு",
    saveScheme: "திட்டத்தை சேமிக்கவும்",
    applicationStatus: "விண்ணப்ப நிலை",
    submitted: "சமர்ப்பிக்கப்பட்டது",
    under_review: "மறுஆய்வில்",
    approved: "அங்கீகரிக்கப்பட்டது",
    disbursed: "வழங்கப்பட்டது",
    selectRole: "உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்",
    citizen: "குடிமகன்",
    officer: "அரசு அதிகாரி",
    publicViewer: "பொது பார்வையாளர்",
  },
  te: {
    appName: "జన్‌సేతు గవ్",
    tagline: "పథకాల అన్వేషణ నుండి ప్రభుత్వ జవాబుదారీతనం వరకు",
    findMySchemes: "నా పథకాలను కనుగొనండి",
    govDashboard: "ప్రభుత్వ డాష్‌బోర్డ్",
    publicView: "ప్రజా పారదర్శకత",
    speakToSearch: "వెతకడానికి మాట్లాడండి",
    orTypeHere: "లేదా ఇక్కడ టైప్ చేయండి...",
    listening: "వింటోంది...",
    searchSchemes: "పథకాలను వెతకండి...",
    mySchemes: "నా పథకాలు",
    profile: "ప్రొఫైల్",
    home: "హోమ్",
    search: "వెతకండి",
    eligibility: "అర్హత",
    benefits: "ప్రయోజనాలు",
    documents: "పత్రాలు",
    applyNow: "ఇప్పుడు దరఖాస్తు చేయండి",
    checkEligibility: "అర్హతను తనిఖీ చేయండి",
    bookmark: "సేవ్ చేయండి",
    bookmarked: "సేవ్ చేయబడింది",
    demoMode: "డెమో మోడ్",
    voicePromptHint: 'చెప్పండి: "నా వద్ద 2 ఎకరాల భూమి ఉంది, వ్యవసాయానికి సహాయం కావాలి"',
    language: "భాష",
    logout: "లాగ్ అవుట్",
    saveScheme: "పథకాన్ని సేవ్ చేయండి",
    applicationStatus: "దరఖాస్తు స్థితి",
    submitted: "సమర్పించబడింది",
    under_review: "సమీక్షలో ఉంది",
    approved: "ఆమోదించబడింది",
    disbursed: "పంపిణీ చేయబడింది",
    selectRole: "మీ పాత్రను ఎంచుకోండి",
    citizen: "పౌరుడు",
    officer: "ప్రభుత్వ అధికారి",
    publicViewer: "ప్రజా వీక్షకుడు",
  },
  kn: {
    appName: "ಜನಸೇತು ಗವ್",
    tagline: "ಯೋಜನೆ ಶೋಧನೆಯಿಂದ ಸರ್ಕಾರಿ ಹೊಣೆಗಾರಿಕೆಯವರೆಗೆ",
    findMySchemes: "ನನ್ನ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    govDashboard: "ಸರ್ಕಾರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    publicView: "ಸಾರ್ವಜನಿಕ ಪಾರದರ್ಶಕತೆ",
    speakToSearch: "ಹುಡುಕಲು ಮಾತನಾಡಿ",
    orTypeHere: "ಅಥವಾ ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...",
    listening: "ಕೇಳುತ್ತಿದೆ...",
    searchSchemes: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...",
    mySchemes: "ನನ್ನ ಯೋಜನೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    home: "ಮುಖಪುಟ",
    search: "ಹುಡುಕಾಟ",
    eligibility: "ಅರ್ಹತೆ",
    benefits: "ಪ್ರಯೋಜನಗಳು",
    documents: "ದಾಖಲೆಗಳು",
    applyNow: "ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    checkEligibility: "ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ",
    bookmark: "ಉಳಿಸಿ",
    bookmarked: "ಉಳಿಸಲಾಗಿದೆ",
    demoMode: "ಡೆಮೊ ಮೋಡ್",
    voicePromptHint: 'ಹೇಳಿ: "ನನ್ನ ಬಳಿ 2 ಎಕರೆ ಭೂಮಿ ಇದೆ, ಕೃಷಿಗೆ ಸಹಾಯ ಬೇಕು"',
    language: "ಭಾಷೆ",
    logout: "ಲಾಗ್ ಔಟ್",
    saveScheme: "ಯೋಜನೆ ಉಳಿಸಿ",
    applicationStatus: "ಅರ್ಜಿ ಸ್ಥಿತಿ",
    submitted: "ಸಲ್ಲಿಸಲಾಗಿದೆ",
    under_review: "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ",
    approved: "ಅನುಮೋದಿಸಲಾಗಿದೆ",
    disbursed: "ವಿತರಿಸಲಾಗಿದೆ",
    selectRole: "ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    citizen: "ನಾಗರಿಕ",
    officer: "ಸರ್ಕಾರಿ ಅಧಿಕಾರಿ",
    publicViewer: "ಸಾರ್ವಜನಿಕ ವೀಕ್ಷಕ",
  },
  pa: {
    appName: "ਜਨਸੇਤੂ ਗਵ",
    tagline: "ਯੋਜਨਾ ਖੋਜ ਤੋਂ ਸਰਕਾਰੀ ਜਵਾਬਦੇਹੀ ਤੱਕ",
    findMySchemes: "ਮੇਰੀਆਂ ਯੋਜਨਾਵਾਂ ਲੱਭੋ",
    govDashboard: "ਸਰਕਾਰੀ ਡੈਸ਼ਬੋਰਡ",
    publicView: "ਜਨਤਕ ਪਾਰਦਰਸ਼ਤਾ",
    speakToSearch: "ਖੋਜਣ ਲਈ ਬੋਲੋ",
    orTypeHere: "ਜਾਂ ਇੱਥੇ ਟਾਈਪ ਕਰੋ...",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ...",
    searchSchemes: "ਯੋਜਨਾਵਾਂ ਖੋਜੋ...",
    mySchemes: "ਮੇਰੀਆਂ ਯੋਜਨਾਵਾਂ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    home: "ਹੋਮ",
    search: "ਖੋਜ",
    eligibility: "ਯੋਗਤਾ",
    benefits: "ਲਾਭ",
    documents: "ਦਸਤਾਵੇਜ਼",
    applyNow: "ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ",
    checkEligibility: "ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ",
    bookmark: "ਸੰਭਾਲੋ",
    bookmarked: "ਸੰਭਾਲਿਆ ਗਿਆ",
    demoMode: "ਡੈਮੋ ਮੋਡ",
    voicePromptHint: 'ਕਹੋ: "ਮੇਰੇ ਕੋਲ 2 ਏਕੜ ਜ਼ਮੀਨ ਹੈ, ਖੇਤੀ ਲਈ ਮਦਦ ਚਾਹੀਦੀ ਹੈ"',
    language: "ਭਾਸ਼ਾ",
    logout: "ਲੌਗ ਆਊਟ",
    saveScheme: "ਯੋਜਨਾ ਸੰਭਾਲੋ",
    applicationStatus: "ਅਰਜ਼ੀ ਦੀ ਸਥਿਤੀ",
    submitted: "ਜਮ੍ਹਾਂ ਕੀਤਾ",
    under_review: "ਸਮੀਖਿਆ ਅਧੀਨ",
    approved: "ਮਨਜ਼ੂਰ",
    disbursed: "ਵੰਡਿਆ ਗਿਆ",
    selectRole: "ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ",
    citizen: "ਨਾਗਰਿਕ",
    officer: "ਸਰਕਾਰੀ ਅਧਿਕਾਰੀ",
    publicViewer: "ਜਨਤਕ ਦਰਸ਼ਕ",
  },
  or: {
    appName: "ଜନସେତୁ ଗଭ",
    tagline: "ଯୋଜନା ଅନ୍ୱେଷଣରୁ ସରକାରୀ ଉତ୍ତରଦାୟିତ୍ୱ ପର୍ଯ୍ୟନ୍ତ",
    findMySchemes: "ମୋର ଯୋଜନାଗୁଡ଼ିକ ଖୋଜନ୍ତୁ",
    govDashboard: "ସରକାରୀ ଡ୍ୟାସବୋର୍ଡ",
    publicView: "ସାର୍ବଜନୀନ ସ୍ୱଚ୍ଛତା",
    speakToSearch: "ଖୋଜିବାକୁ କୁହନ୍ତୁ",
    orTypeHere: "କିମ୍ବା ଏଠାରେ ଟାଇପ୍ କରନ୍ତୁ...",
    listening: "ଶୁଣୁଛି...",
    searchSchemes: "ଯୋଜନାଗୁଡ଼ିକ ଖୋଜନ୍ତୁ...",
    mySchemes: "ମୋର ଯୋଜନାଗୁଡ଼ିକ",
    profile: "ପ୍ରୋଫାଇଲ୍",
    home: "ମୂଳପୃଷ୍ଠା",
    search: "ଖୋଜ",
    eligibility: "ଯୋଗ୍ୟତା",
    benefits: "ଲାଭ",
    documents: "ଦଲିଲ",
    applyNow: "ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ",
    checkEligibility: "ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ",
    bookmark: "ସେଭ୍ କରନ୍ତୁ",
    bookmarked: "ସେଭ୍ ହୋଇଛି",
    demoMode: "ଡେମୋ ମୋଡ୍",
    voicePromptHint: 'କୁହନ୍ତୁ: "ମୋର 2 ଏକର ଜମି ଅଛି, ଚାଷ ପାଇଁ ସାହାଯ୍ୟ ଦରକାର"',
    language: "ଭାଷା",
    logout: "ଲଗ୍ ଆଉଟ୍",
    saveScheme: "ଯୋଜନା ସେଭ୍ କରନ୍ତୁ",
    applicationStatus: "ଆବେଦନ ସ୍ଥିତି",
    submitted: "ଦାଖଲ ହୋଇଛି",
    under_review: "ସମୀକ୍ଷାଧୀନ",
    approved: "ଅନୁମୋଦିତ",
    disbursed: "ବଣ୍ଟିତ",
    selectRole: "ଆପଣଙ୍କ ଭୂମିକା ବାଛନ୍ତୁ",
    citizen: "ନାଗରିକ",
    officer: "ସରକାରୀ ଅଧିକାରୀ",
    publicViewer: "ସାର୍ବଜନୀନ ଦର୍ଶକ",
  },
  ur: {
    appName: "جن سیتو گو",
    tagline: "اسکیم کی دریافت سے حکومتی جوابدہی تک",
    findMySchemes: "میری اسکیمیں تلاش کریں",
    govDashboard: "حکومتی ڈیش بورڈ",
    publicView: "عوامی شفافیت",
    speakToSearch: "تلاش کے لیے بولیں",
    orTypeHere: "یا یہاں ٹائپ کریں...",
    listening: "سن رہا ہے...",
    searchSchemes: "اسکیمیں تلاش کریں...",
    mySchemes: "میری اسکیمیں",
    profile: "پروفائل",
    home: "ہوم",
    search: "تلاش",
    eligibility: "اہلیت",
    benefits: "فوائد",
    documents: "دستاویزات",
    applyNow: "ابھی درخواست دیں",
    checkEligibility: "اہلیت چیک کریں",
    bookmark: "محفوظ کریں",
    bookmarked: "محفوظ شدہ",
    demoMode: "ڈیمو موڈ",
    voicePromptHint: 'کہیں: "میرے پاس 2 ایکڑ زمین ہے، کھیتی کے لیے مدد چاہیے"',
    language: "زبان",
    logout: "لاگ آؤٹ",
    saveScheme: "اسکیم محفوظ کریں",
    applicationStatus: "درخواست کی حیثیت",
    submitted: "جمع کرایا گیا",
    under_review: "زیر جائزہ",
    approved: "منظور شدہ",
    disbursed: "تقسیم شدہ",
    selectRole: "اپنا کردار منتخب کریں",
    citizen: "شہری",
    officer: "سرکاری افسر",
    publicViewer: "عوامی ناظر",
  },
  ne: {
    appName: "जनसेतु गभ",
    tagline: "योजना खोजबाट सरकारी जवाफदेहितासम्म",
    findMySchemes: "मेरा योजनाहरू खोज्नुहोस्",
    govDashboard: "सरकारी ड्यासबोर्ड",
    publicView: "सार्वजनिक पारदर्शिता",
    speakToSearch: "खोज्न बोल्नुहोस्",
    orTypeHere: "वा यहाँ टाइप गर्नुहोस्...",
    listening: "सुन्दै...",
    searchSchemes: "योजनाहरू खोज्नुहोस्...",
    mySchemes: "मेरा योजनाहरू",
    profile: "प्रोफाइल",
    home: "गृहपृष्ठ",
    search: "खोज",
    eligibility: "योग्यता",
    benefits: "लाभहरू",
    documents: "कागजातहरू",
    applyNow: "अहिले आवेदन दिनुहोस्",
    checkEligibility: "योग्यता जाँच गर्नुहोस्",
    bookmark: "बुकमार्क गर्नुहोस्",
    bookmarked: "बुकमार्क गरिएको",
    demoMode: "डेमो मोड",
    voicePromptHint: 'भन्नुहोस्: "मसँग 2 बिघा जमिन छ, खेतीका लागि मद्दत चाहियो"',
    language: "भाषा",
    logout: "लगआउट",
    saveScheme: "योजना बचत गर्नुहोस्",
    applicationStatus: "आवेदन स्थिति",
    submitted: "पेश गरियो",
    under_review: "समीक्षामा",
    approved: "स्वीकृत",
    disbursed: "वितरण गरियो",
    selectRole: "आफ्नो भूमिका छान्नुहोस्",
    citizen: "नागरिक",
    officer: "सरकारी अधिकारी",
    publicViewer: "सार्वजनिक दर्शक",
  },
  ml: {
    appName: "ജൻസേതു ഗവ്",
    tagline: "പദ്ധതി കണ്ടെത്തലിൽ നിന്ന് സർക്കാർ ഉത്തരവാദിത്തത്തിലേക്ക്",
    findMySchemes: "എന്റെ പദ്ധതികൾ കണ്ടെത്തുക",
    govDashboard: "സർക്കാർ ഡാഷ്‌ബോർഡ്",
    publicView: "പൊതു സുതാര്യത",
    speakToSearch: "തിരയാൻ സംസാരിക്കുക",
    orTypeHere: "അല്ലെങ്കിൽ ഇവിടെ ടൈപ്പ് ചെയ്യുക...",
    listening: "കേൾക്കുന്നു...",
    searchSchemes: "പദ്ധതികൾ തിരയുക...",
    mySchemes: "എന്റെ പദ്ധതികൾ",
    profile: "പ്രൊഫൈൽ",
    home: "ഹോം",
    search: "തിരയൽ",
    eligibility: "യോഗ്യത",
    benefits: "ആനുകൂല്യങ്ങൾ",
    documents: "രേഖകൾ",
    applyNow: "ഇപ്പോൾ അപേക്ഷിക്കുക",
    checkEligibility: "യോഗ്യത പരിശോധിക്കുക",
    bookmark: "സേവ് ചെയ്യുക",
    bookmarked: "സേവ് ചെയ്തു",
    demoMode: "ഡെമോ മോഡ്",
    voicePromptHint: 'പറയുക: "എനിക്ക് 2 ഏക്കർ ഭൂമിയുണ്ട്, കൃഷിക്ക് സഹായം വേണം"',
    language: "ഭാഷ",
    logout: "ലോഗ് ഔട്ട്",
    saveScheme: "പദ്ധതി സേവ് ചെയ്യുക",
    applicationStatus: "അപേക്ഷയുടെ നില",
    submitted: "സമർപ്പിച്ചു",
    under_review: "അവലോകനത്തിൽ",
    approved: "അംഗീകരിച്ചു",
    disbursed: "വിതരണം ചെയ്തു",
    selectRole: "നിങ്ങളുടെ പങ്ക് തിരഞ്ഞെടുക്കുക",
    citizen: "പൗരൻ",
    officer: "സർക്കാർ ഉദ്യോഗസ്ഥൻ",
    publicViewer: "പൊതു കാഴ്ചക്കാരൻ",
  },
  sa: {
    appName: "जनसेतु गव",
    tagline: "योजनान्वेषणात् सरकारी उत्तरदायित्वं यावत्",
    findMySchemes: "मम योजनाः अन्विष्यताम्",
    govDashboard: "सरकारी फलकम्",
    publicView: "सार्वजनिक पारदर्शिता",
    speakToSearch: "अन्वेषणाय वदतु",
    orTypeHere: "अथवा अत्र लिखतु...",
    listening: "श्रूयते...",
    searchSchemes: "योजनाः अन्विष्यताम्...",
    mySchemes: "मम योजनाः",
    profile: "परिचयपत्रम्",
    home: "गृहम्",
    search: "अन्वेषणम्",
    eligibility: "योग्यता",
    benefits: "लाभाः",
    documents: "दस्तावेजाः",
    applyNow: "इदानीं आवेदनं कुरुत",
    checkEligibility: "योग्यतां परीक्षताम्",
    bookmark: "सुरक्षितं करोतु",
    bookmarked: "सुरक्षितम्",
    demoMode: "प्रदर्शन प्रकारः",
    voicePromptHint: 'वदतु: "मम द्वे एकरभूमिः अस्ति, कृषये सहायता आवश्यकी"',
    language: "भाषा",
    logout: "निर्गमनम्",
    saveScheme: "योजनां सुरक्षितं करोतु",
    applicationStatus: "आवेदन स्थितिः",
    submitted: "समर्पितम्",
    under_review: "पुनरीक्षणे",
    approved: "अनुमोदितम्",
    disbursed: "वितरितम्",
    selectRole: "स्वस्य भूमिकां चिनुत",
    citizen: "नागरिकः",
    officer: "सरकारी अधिकारी",
    publicViewer: "सार्वजनिक दर्शकः",
  },
  kok: {
    appName: "जनसेतू गव",
    tagline: "येवजण सोदणाच्यान सरकारी जबाबदारेमेरेन",
    findMySchemes: "म्हज्यो येवजण्यो सोदात",
    govDashboard: "सरकारी डॅशबोर्ड",
    publicView: "सार्वजनीक पारदर्शकता",
    speakToSearch: "सोदपाक उलयात",
    orTypeHere: "वा हांगा टायप करात...",
    listening: "आयकता...",
    searchSchemes: "येवजण्यो सोदात...",
    mySchemes: "म्हज्यो येवजण्यो",
    profile: "प्रोफायल",
    home: "घर",
    search: "सोद",
    eligibility: "पात्रताय",
    benefits: "फायदे",
    documents: "कागदपत्रां",
    applyNow: "आतां अर्ज करात",
    checkEligibility: "पात्रताय तपासात",
    bookmark: "जतनाय करात",
    bookmarked: "जतनाय केलां",
    demoMode: "डेमो मोड",
    voicePromptHint: 'सांगात: "म्हजेकडेन 2 एकर जमीन आसा, शेतीक मजत जाय"',
    language: "भास",
    logout: "भायर सरात",
    saveScheme: "येवजण जतनाय करात",
    applicationStatus: "अर्जाची स्थिती",
    submitted: "सादर केलां",
    under_review: "फेरविचारांत",
    approved: "मान्य केलां",
    disbursed: "वांटलां",
    selectRole: "तुमची भुमिका निवडात",
    citizen: "नागरीक",
    officer: "सरकारी अधिकारी",
    publicViewer: "सार्वजनीक पळोवपी",
  },
  mai: {
    appName: "जनसेतु गव",
    tagline: "योजना खोज सँ सरकारी जबाबदेहि धरि",
    findMySchemes: "हमर योजना सभ खोजू",
    govDashboard: "सरकारी डैशबोर्ड",
    publicView: "सार्वजनिक पारदर्शिता",
    speakToSearch: "खोजबाक लेल बाजू",
    orTypeHere: "अथवा इएठ टाइप करू...",
    listening: "सुनि रहल अछि...",
    searchSchemes: "योजना खोजू...",
    mySchemes: "हमर योजना सभ",
    profile: "प्रोफाइल",
    home: "गृह",
    search: "खोज",
    eligibility: "योग्यता",
    benefits: "लाभ",
    documents: "कागजात",
    applyNow: "एखन आवेदन करू",
    checkEligibility: "योग्यता जाँचू",
    bookmark: "सहेजू",
    bookmarked: "सहेजल गेल",
    demoMode: "डेमो मोड",
    voicePromptHint: 'कहू: "हमरा लग 2 एकड़ जमीन अछि, खेती लेल मदति चाही"',
    language: "भाषा",
    logout: "लॉग आउट",
    saveScheme: "योजना सहेजू",
    applicationStatus: "आवेदन स्थिति",
    submitted: "जमा कएल गेल",
    under_review: "समीक्षाधीन",
    approved: "स्वीकृत",
    disbursed: "वितरित",
    selectRole: "अपन भूमिका चुनू",
    citizen: "नागरिक",
    officer: "सरकारी पदाधिकारी",
    publicViewer: "सार्वजनिक दर्शक",
  },
};
// ── Category label translations (fixed list) ────────────────
export const CATEGORY_LABELS: Record<LangCode, Record<string, string>> = {
  en: { Agriculture: "Agriculture", Education: "Education", "Women & Child": "Women & Child", Health: "Health", Housing: "Housing", Employment: "Employment", MSME: "MSME", "Senior Citizens": "Senior Citizens", Scholarships: "Scholarships", "Rural Development": "Rural Development" },
  hi: { Agriculture: "कृषि", Education: "शिक्षा", "Women & Child": "महिला एवं बाल", Health: "स्वास्थ्य", Housing: "आवास", Employment: "रोजगार", MSME: "एमएसएमई", "Senior Citizens": "वरिष्ठ नागरिक", Scholarships: "छात्रवृत्ति", "Rural Development": "ग्रामीण विकास" },
  as: { Agriculture: "কৃষি", Education: "শিক্ষা", "Women & Child": "মহিলা আৰু শিশু", Health: "স্বাস্থ্য", Housing: "আবাসন", Employment: "নিয়োগ", MSME: "এমএছএমই", "Senior Citizens": "বৃদ্ধ নাগৰিক", Scholarships: "বৃত্তি", "Rural Development": "গ্ৰাম্য উন্নয়ন" },
  bn: { Agriculture: "কৃষি", Education: "শিক্ষা", "Women & Child": "নারী ও শিশু", Health: "স্বাস্থ্য", Housing: "আবাসন", Employment: "কর্মসংস্থান", MSME: "এমএসএমই", "Senior Citizens": "প্রবীণ নাগরিক", Scholarships: "বৃত্তি", "Rural Development": "গ্রামীণ উন্নয়ন" },
  mr: { Agriculture: "शेती", Education: "शिक्षण", "Women & Child": "महिला व बालक", Health: "आरोग्य", Housing: "गृहनिर्माण", Employment: "रोजगार", MSME: "एमएसएमई", "Senior Citizens": "ज्येष्ठ नागरिक", Scholarships: "शिष्यवृत्ती", "Rural Development": "ग्रामीण विकास" },
  gu: { Agriculture: "ખેતી", Education: "શિક્ષણ", "Women & Child": "મહિલા અને બાળ", Health: "આરોગ્ય", Housing: "આવાસ", Employment: "રોજગાર", MSME: "એમએસએમઈ", "Senior Citizens": "વરિષ્ઠ નાગરિકો", Scholarships: "શિષ્યવૃત્તિ", "Rural Development": "ગ્રામીણ વિકાસ" },
  ta: { Agriculture: "வேளாண்மை", Education: "கல்வி", "Women & Child": "பெண்கள் & குழந்தைகள்", Health: "சுகாதாரம்", Housing: "வீட்டுவசதி", Employment: "வேலைவாய்ப்பு", MSME: "எம்எஸ்எம்இ", "Senior Citizens": "மூத்த குடிமக்கள்", Scholarships: "உதவித்தொகை", "Rural Development": "கிராமப்புற வளர்ச்சி" },
  te: { Agriculture: "వ్యవసాయం", Education: "విద్య", "Women & Child": "మహిళలు & పిల్లలు", Health: "ఆరోగ్యం", Housing: "గృహనిర్మాణం", Employment: "ఉపాధి", MSME: "ఎంఎస్ఎంఈ", "Senior Citizens": "సీనియర్ సిటిజన్లు", Scholarships: "స్కాలర్‌షిప్‌లు", "Rural Development": "గ్రామీణాభివృద్ధి" },
  kn: { Agriculture: "ಕೃಷಿ", Education: "ಶಿಕ್ಷಣ", "Women & Child": "ಮಹಿಳೆ ಮತ್ತು ಮಕ್ಕಳು", Health: "ಆರೋಗ್ಯ", Housing: "ವಸತಿ", Employment: "ಉದ್ಯೋಗ", MSME: "ಎಂಎಸ್‌ಎಂಇ", "Senior Citizens": "ಹಿರಿಯ ನಾಗರಿಕರು", Scholarships: "ವಿದ್ಯಾರ್ಥಿವೇತನ", "Rural Development": "ಗ್ರಾಮೀಣ ಅಭಿವೃದ್ಧಿ" },
  pa: { Agriculture: "ਖੇਤੀਬਾੜੀ", Education: "ਸਿੱਖਿਆ", "Women & Child": "ਮਹਿਲਾ ਅਤੇ ਬਾਲ", Health: "ਸਿਹਤ", Housing: "ਰਿਹਾਇਸ਼", Employment: "ਰੁਜ਼ਗਾਰ", MSME: "ਐਮਐਸਐਮਈ", "Senior Citizens": "ਸੀਨੀਅਰ ਨਾਗਰਿਕ", Scholarships: "ਸਕਾਲਰਸ਼ਿਪ", "Rural Development": "ਪੇਂਡੂ ਵਿਕਾਸ" },
  or: { Agriculture: "କୃଷି", Education: "ଶିକ୍ଷା", "Women & Child": "ମହିଳା ଓ ଶିଶୁ", Health: "ସ୍ୱାସ୍ଥ୍ୟ", Housing: "ଗୃହନିର୍ମାଣ", Employment: "ନିଯୁକ୍ତି", MSME: "ଏମଏସଏମଇ", "Senior Citizens": "ବରିଷ୍ଠ ନାଗରିକ", Scholarships: "ବୃତ୍ତି", "Rural Development": "ଗ୍ରାମୀଣ ବିକାଶ" },
  ur: { Agriculture: "زراعت", Education: "تعلیم", "Women & Child": "خواتین اور بچے", Health: "صحت", Housing: "رہائش", Employment: "روزگار", MSME: "ایم ایس ایم ای", "Senior Citizens": "سینئر شہری", Scholarships: "وظیفہ", "Rural Development": "دیہی ترقی" },
  ne: { Agriculture: "कृषि", Education: "शिक्षा", "Women & Child": "महिला र बालबालिका", Health: "स्वास्थ्य", Housing: "आवास", Employment: "रोजगार", MSME: "एमएसएमई", "Senior Citizens": "ज्येष्ठ नागरिक", Scholarships: "छात्रवृत्ति", "Rural Development": "ग्रामीण विकास" },
  ml: { Agriculture: "കൃഷി", Education: "വിദ്യാഭ്യാസം", "Women & Child": "സ്ത്രീകളും കുട്ടികളും", Health: "ആരോഗ്യം", Housing: "ഭവനനിർമ്മാണം", Employment: "തൊഴിൽ", MSME: "എംഎസ്എംഇ", "Senior Citizens": "മുതിർന്ന പൗരന്മാർ", Scholarships: "സ്കോളർഷിപ്പുകൾ", "Rural Development": "ഗ്രാമവികസനം" },
  sa: { Agriculture: "कृषिः", Education: "शिक्षा", "Women & Child": "महिला बालाश्च", Health: "स्वास्थ्यम्", Housing: "आवासः", Employment: "नियोजनम्", MSME: "लघुउद्योगः", "Senior Citizens": "वृद्धनागरिकाः", Scholarships: "छात्रवृत्तिः", "Rural Development": "ग्रामविकासः" },
  kok: { Agriculture: "शेती", Education: "शिक्षण", "Women & Child": "बायल आनी भुरगीं", Health: "भलायकी", Housing: "घरबांधावळ", Employment: "वावर", MSME: "एमएसएमई", "Senior Citizens": "जेष्ठ नागरीक", Scholarships: "शिश्यवृत्ती", "Rural Development": "ग्रामीण उदरगत" },
  mai: { Agriculture: "खेती", Education: "शिक्षा", "Women & Child": "महिला आ बाल", Health: "स्वास्थ्य", Housing: "आवास", Employment: "रोजगार", MSME: "एमएसएमई", "Senior Citizens": "वरिष्ठ नागरिक", Scholarships: "छात्रवृत्ति", "Rural Development": "ग्रामीण विकास" },
};
 
// ── Lifecycle step translations (fixed list) ─────────────────
export const LIFECYCLE_LABELS: Record<LangCode, Record<string, string>> = {
  en: { Discover: "Discover", "Check Eligibility": "Check Eligibility", Apply: "Apply", "Govt Funding": "Govt Funding", Implementation: "Implementation", "Public Transparency": "Public Transparency" },
  hi: { Discover: "खोजें", "Check Eligibility": "पात्रता जांचें", Apply: "आवेदन करें", "Govt Funding": "सरकारी फंडिंग", Implementation: "कार्यान्वयन", "Public Transparency": "सार्वजनिक पारदर्शिता" },
  as: { Discover: "বিচাৰক", "Check Eligibility": "যোগ্যতা পৰীক্ষা কৰক", Apply: "আবেদন কৰক", "Govt Funding": "চৰকাৰী ফাণ্ডিং", Implementation: "প্ৰয়োগ", "Public Transparency": "ৰাজহুৱা স্বচ্ছতা" },
  bn: { Discover: "খুঁজুন", "Check Eligibility": "যোগ্যতা যাচাই করুন", Apply: "আবেদন করুন", "Govt Funding": "সরকারি তহবিল", Implementation: "বাস্তবায়ন", "Public Transparency": "সার্বজনীন স্বচ্ছতা" },
  mr: { Discover: "शोधा", "Check Eligibility": "पात्रता तपासा", Apply: "अर्ज करा", "Govt Funding": "सरकारी निधी", Implementation: "अंमलबजावणी", "Public Transparency": "सार्वजनिक पारदर्शकता" },
  gu: { Discover: "શોધો", "Check Eligibility": "પાત્રતા ચકાસો", Apply: "અરજી કરો", "Govt Funding": "સરકારી ભંડોળ", Implementation: "અમલીકરણ", "Public Transparency": "જાહેર પારદર્શિતા" },
  ta: { Discover: "கண்டறியவும்", "Check Eligibility": "தகுதியை சரிபார்க்கவும்", Apply: "விண்ணப்பிக்கவும்", "Govt Funding": "அரசு நிதி", Implementation: "செயல்படுத்தல்", "Public Transparency": "பொது வெளிப்படைத்தன்மை" },
  te: { Discover: "కనుగొనండి", "Check Eligibility": "అర్హతను తనిఖీ చేయండి", Apply: "దరఖాస్తు చేయండి", "Govt Funding": "ప్రభుత్వ నిధులు", Implementation: "అమలు", "Public Transparency": "ప్రజా పారదర్శకత" },
  kn: { Discover: "ಹುಡುಕಿ", "Check Eligibility": "ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ", Apply: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ", "Govt Funding": "ಸರ್ಕಾರಿ ಧನಸಹಾಯ", Implementation: "ಅನುಷ್ಠಾನ", "Public Transparency": "ಸಾರ್ವಜನಿಕ ಪಾರದರ್ಶಕತೆ" },
  pa: { Discover: "ਖੋਜੋ", "Check Eligibility": "ਯੋਗਤਾ ਜਾਂਚੋ", Apply: "ਅਰਜ਼ੀ ਦਿਓ", "Govt Funding": "ਸਰਕਾਰੀ ਫੰਡਿੰਗ", Implementation: "ਲਾਗੂਕਰਨ", "Public Transparency": "ਜਨਤਕ ਪਾਰਦਰਸ਼ਤਾ" },
  or: { Discover: "ଖୋଜନ୍ତୁ", "Check Eligibility": "ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ", Apply: "ଆବେଦନ କରନ୍ତୁ", "Govt Funding": "ସରକାରୀ ଅର୍ଥ ପ୍ରଦାନ", Implementation: "କାର୍ଯ୍ୟକାରିତା", "Public Transparency": "ସାର୍ବଜନୀନ ସ୍ୱଚ୍ଛତା" },
  ur: { Discover: "تلاش کریں", "Check Eligibility": "اہلیت چیک کریں", Apply: "درخواست دیں", "Govt Funding": "سرکاری فنڈنگ", Implementation: "عملدرآمد", "Public Transparency": "عوامی شفافیت" },
  ne: { Discover: "खोज्नुहोस्", "Check Eligibility": "योग्यता जाँच्नुहोस्", Apply: "आवेदन दिनुहोस्", "Govt Funding": "सरकारी कोष", Implementation: "कार्यान्वयन", "Public Transparency": "सार्वजनिक पारदर्शिता" },
  ml: { Discover: "കണ്ടെത്തുക", "Check Eligibility": "യോഗ്യത പരിശോധിക്കുക", Apply: "അപേക്ഷിക്കുക", "Govt Funding": "സർക്കാർ ധനസഹായം", Implementation: "നടപ്പാക്കൽ", "Public Transparency": "പൊതു സുതാര്യത" },
  sa: { Discover: "अन्विष्यताम्", "Check Eligibility": "योग्यतां परीक्षताम्", Apply: "आवेदनं कुरुत", "Govt Funding": "सरकारी निधिः", Implementation: "कार्यान्वयनम्", "Public Transparency": "सार्वजनिक पारदर्शिता" },
  kok: { Discover: "सोदात", "Check Eligibility": "पात्रताय तपासात", Apply: "अर्ज करात", "Govt Funding": "सरकारी निधी", Implementation: "अंमलबजावणी", "Public Transparency": "सार्वजनीक पारदर्शकता" },
  mai: { Discover: "खोजू", "Check Eligibility": "योग्यता जाँचू", Apply: "आवेदन करू", "Govt Funding": "सरकारी निधि", Implementation: "कार्यान्वयन", "Public Transparency": "सार्वजनिक पारदर्शिता" },
};
 
export function getCategoryLabel(category: string, lang: LangCode): string {
  return CATEGORY_LABELS[lang]?.[category] ?? category;
}
 
export function getLifecycleLabel(step: string, lang: LangCode): string {
  return LIFECYCLE_LABELS[lang]?.[step] ?? step;
}
 